### ISSUE TITLE
No Occupancy Detected After Homebridge .26

### ISSUE THREAD

**Issue by erfind** [PeteLawrence/homebridge-people#79]
Is anyone else having this issue?

**Comment by DJay79** [comment]
Same here. And because of this my automatic routines are going crazy. 
Hopefully this can be fixed.

**Comment by erfind** [comment]
You can revert until a solution is found:

sudo npm -g install homebridge@0.4.25

**Comment by pdlove** [comment]
I've submitted a PR for this issue. Honestly, if shouldn't work with any homebridge after 0.4.24 because of the new data validation routines.
By the way, awesome plugin. I don't know how this missed getting into my every day install. Will definitely get this setup when my wife gets home with her phone.

**Comment by PeteLawrence** [comment]
I've just released version 0.6.1 which fixes this.  Credit goes to @pdlove.

**Comment by skrollme** [comment]
I'm still facing problems with the push of occupancy-statechanges to HomeKit (Home.app).
- For versions **<= homebridge@0.4.25** the state-changes (testing with manually triggered web hook events) immediately popup at the Home.app >> **Realtime** 👍 
- For **> homebridge@0.4.26** this stopped working. The changed state only updates after a refresh (Home.app close/resume) >> **Breaks most automations** 👎 

A difference I noticed on homebridge startup:
The accessories' debug-logs state a different behavior between the versions. Focus on the order of _unregister_ and _register_:
**<= homebridge@0.4.25**
```
...
Accessory [Homebridge MB] Processing characteristic set: [{"aid":6,"iid":9,"ev":true}] +1ms
Accessory [Homebridge MB] Registering Characteristic "Occupancy Detected" for events +1ms
EventedHTTPServer [::ffff:192.168.178.27] HTTP Response is finished +1ms
EventedHTTPServer [::ffff:192.168.178.27] HTTP request: /characteristics +6ms
HAPServer [DE:AD:BE:EF:47:13] HAP Request: PUT /characteristics +0ms
Accessory [Homebridge MB] Processing characteristic set: [{"aid":6,"iid":9,"ev":false}] +1ms
Accessory [Homebridge MB] Unregistering Characteristic "Occupancy Detected" for events +0ms
...
```

**> homebridge@0.4.25**
```
...
Accessory [Homebridge MB] Processing characteristic set: [{"aid":8,"iid":9,"ev":false}] +1ms
Accessory [Homebridge MB] Unregistering Characteristic "Occupancy Detected" for events +1ms
EventedHTTPServer [::ffff:192.168.178.38] HTTP Response is finished +0ms

...  // lots of other stuff but only from 'EventedHTTPServer' and 'HAPServer'

Accessory [Homebridge MB] Processing characteristic set: [{"aid":8,"iid":9,"ev":true}] +0ms
Accessory [Homebridge MB] Registering Characteristic "Occupancy Detected" for events +0ms
EventedHTTPServer [::ffff:192.168.178.27] HTTP Response is finished +1ms
...
```

If this is important: I'm on node 8.4.0 on a raspberryPi

**Comment by erfind** [comment]
I agree I’m having the same issue.

**Comment by GatoPharaoh** [comment]
Same problem here - somebody found a solution for this?

**Comment by pdlove** [comment]
I believe it in registers when it receives an unexpected response. Have you tried it with the week old update that was recently done? We cleared up a true/false problem with what can only be described as a bug in HomeKit/Siri.

**Comment by GatoPharaoh** [comment]
Got it working with `homebridge@0.4.28` and `homebridge-people@0.6.1`
Thank you @pdlove

**Comment by stephanroslen** [comment]
@skrollme, @erfind, @GatoPharaoh: I fixed this issue with https://github.com/PeteLawrence/homebridge-people/pull/83

**Comment by skrollme** [comment]
Awesome, @stephanroslen ! I will give it a try.
